
package proxy;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import jakarta.xml.ws.Service;
import jakarta.xml.ws.WebEndpoint;
import jakarta.xml.ws.WebServiceClient;
import jakarta.xml.ws.WebServiceException;
import jakarta.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.3.2
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "BibliothequeWS", targetNamespace = "http://ws/", wsdlLocation = "http://localhost:8080/BibliothequeWS?wsdl")
public class BibliothequeWS_Service
    extends Service
{

    private final static URL BIBLIOTHEQUEWS_WSDL_LOCATION;
    private final static WebServiceException BIBLIOTHEQUEWS_EXCEPTION;
    private final static QName BIBLIOTHEQUEWS_QNAME = new QName("http://ws/", "BibliothequeWS");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:8080/BibliothequeWS?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        BIBLIOTHEQUEWS_WSDL_LOCATION = url;
        BIBLIOTHEQUEWS_EXCEPTION = e;
    }

    public BibliothequeWS_Service() {
        super(__getWsdlLocation(), BIBLIOTHEQUEWS_QNAME);
    }

    public BibliothequeWS_Service(WebServiceFeature... features) {
        super(__getWsdlLocation(), BIBLIOTHEQUEWS_QNAME, features);
    }

    public BibliothequeWS_Service(URL wsdlLocation) {
        super(wsdlLocation, BIBLIOTHEQUEWS_QNAME);
    }

    public BibliothequeWS_Service(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, BIBLIOTHEQUEWS_QNAME, features);
    }

    public BibliothequeWS_Service(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public BibliothequeWS_Service(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns BibliothequeWS
     */
    @WebEndpoint(name = "BibliothequeWSPort")
    public BibliothequeWS getBibliothequeWSPort() {
        return super.getPort(new QName("http://ws/", "BibliothequeWSPort"), BibliothequeWS.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns BibliothequeWS
     */
    @WebEndpoint(name = "BibliothequeWSPort")
    public BibliothequeWS getBibliothequeWSPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://ws/", "BibliothequeWSPort"), BibliothequeWS.class, features);
    }

    private static URL __getWsdlLocation() {
        if (BIBLIOTHEQUEWS_EXCEPTION!= null) {
            throw BIBLIOTHEQUEWS_EXCEPTION;
        }
        return BIBLIOTHEQUEWS_WSDL_LOCATION;
    }

}
