
package proxy;

import java.util.List;
import jakarta.jws.WebMethod;
import jakarta.jws.WebParam;
import jakarta.jws.WebResult;
import jakarta.jws.WebService;
import jakarta.xml.bind.annotation.XmlSeeAlso;
import jakarta.xml.ws.Action;
import jakarta.xml.ws.RequestWrapper;
import jakarta.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.3.2
 * Generated source version: 2.2
 * 
 */
@WebService(name = "BibliothequeWS", targetNamespace = "http://ws/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface BibliothequeWS {


    /**
     * 
     * @param isbn
     * @return
     *     returns proxy.Livre
     */
    @WebMethod(operationName = "RechercherLivreParIsbn")
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "RechercherLivreParIsbn", targetNamespace = "http://ws/", className = "proxy.RechercherLivreParIsbn")
    @ResponseWrapper(localName = "RechercherLivreParIsbnResponse", targetNamespace = "http://ws/", className = "proxy.RechercherLivreParIsbnResponse")
    @Action(input = "http://ws/BibliothequeWS/RechercherLivreParIsbnRequest", output = "http://ws/BibliothequeWS/RechercherLivreParIsbnResponse")
    public Livre rechercherLivreParIsbn(
        @WebParam(name = "isbn", targetNamespace = "")
        String isbn);

    /**
     * 
     * @param livre
     * @return
     *     returns boolean
     */
    @WebMethod(operationName = "AjouterNouveauLivre")
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "AjouterNouveauLivre", targetNamespace = "http://ws/", className = "proxy.AjouterNouveauLivre")
    @ResponseWrapper(localName = "AjouterNouveauLivreResponse", targetNamespace = "http://ws/", className = "proxy.AjouterNouveauLivreResponse")
    @Action(input = "http://ws/BibliothequeWS/AjouterNouveauLivreRequest", output = "http://ws/BibliothequeWS/AjouterNouveauLivreResponse")
    public boolean ajouterNouveauLivre(
        @WebParam(name = "livre", targetNamespace = "")
        Livre livre);

    /**
     * 
     * @return
     *     returns java.util.List<proxy.Livre>
     */
    @WebMethod(operationName = "ListerLivres")
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "ListerLivres", targetNamespace = "http://ws/", className = "proxy.ListerLivres")
    @ResponseWrapper(localName = "ListerLivresResponse", targetNamespace = "http://ws/", className = "proxy.ListerLivresResponse")
    @Action(input = "http://ws/BibliothequeWS/ListerLivresRequest", output = "http://ws/BibliothequeWS/ListerLivresResponse")
    public List<Livre> listerLivres();

}
