spring.application.name=tp8
server.port=8081

# JWT Configuration
spring.security.oauth2.resourceserver.jwt.issuer-uri=http://localhost/fake-issuer
spring.security.oauth2.resourceserver.jwt.jwk-set-uri=http://localhost/fake-issuer/.well-known/jwks.json
